Revert "disable upgrades to 26 on 32-bit"
nextcloud/updater pull request #464
Opened 2023-02-07 13:45 UTC by come-nc

Reverts #446

2023-02-07 13:46 UTC, come-nc commented
/backport to stable25

2023-02-07 14:28 UTC, szaimen commented on index.php
> +
```suggestion
```

2023-02-07 14:28 UTC, szaimen requested changes
also you deleted the updater.phar?

2023-02-08 09:16 UTC, come-nc commented
> also you deleted the updater.phar?

No?

2023-02-08 09:17 UTC, szaimen approved these changes
LGTM but didnt test

2023-02-09 10:15 UTC, blizzz approved these changes

2023-02-09 10:15 UTC, merged