tests(matrix): update nextcloud stable versions
nextcloud/updater pull request #489
Opened 2023-09-12 11:08 UTC by blizzz

2023-09-12 12:19 UTC, juliushaertl approved these changes

2023-09-12 12:52 UTC, come-nc approved these changes

2023-09-12 12:54 UTC, come-nc commented
Actually, you cannot do it like that. Tests are in Makefile and tests/features.

2023-09-12 12:55 UTC, come-nc requested changes
If really needed adapt the test suite.

2023-09-14 10:02 UTC, blizzz commented
already forget about this PR :smiling_face_with_tear:  obsolete

2023-09-14 10:02 UTC, closed without merging