fix(integrity): expect pkg mgmt files
nextcloud/updater pull request #490
Opened 2023-09-12 11:19 UTC by blizzz

backport of #488

2023-09-12 11:20 UTC, blizzz commented
Tested on an instance that was having the issue, and it fixes it.

2023-09-12 11:53 UTC, AndyScherzinger approved these changes

2023-09-12 12:14 UTC, juliushaertl approved these changes

2023-09-12 12:52 UTC, come-nc commented
CI is not happy.

When doing "composer i" I end up with files removed from git, is that expected?

2023-09-13 11:07 UTC, blizzz commented
> CI is not happy.
> 
> When doing "composer i" I end up with files removed from git, is that expected?

Sounds strange, what would it want to remove? 

The makefile (and also tests) differ from master, it surely is worth to streamline them as well.

2023-09-13 12:19 UTC, blizzz commented
Pushed minimal adjustments to the tests.

2023-09-13 13:20 UTC, blizzz commented
"minimal"… tbc

2023-09-13 19:35 UTC, blizzz commented
totally nuts. Why don't I copy over test definition from master? It succeeds even on 8.2 for unknown reasons, but it does not test against 27. Still might give it a try tomorrow, this is frustration. In this repo we almost never have PRs against stable branches…

2023-09-14 07:00 UTC, come-nc requested changes

2023-09-14 07:00 UTC, come-nc commented on tests/features/master.feature
Feels weird to stop testing that, support for daily channel is a feature of the updater.

2023-09-14 07:00 UTC, come-nc commented on tests/features/stable20.feature
> -  Scenario: Update is available but unexpected folder found - 20.0.7 to 20.0.8
unexpected folder here.

All these tests should be kept IMO since they test features of the updater.

2023-09-14 07:06 UTC, come-nc commented
Also why the symfony/console bump in stable27 that was not done in master first?

2023-09-14 07:07 UTC, come-nc commented
> > CI is not happy.
> > When doing "composer i" I end up with files removed from git, is that expected?
> 
> Sounds strange, what would it want to remove?
> 
> The makefile (and also tests) differ from master, it surely is worth to streamline them as well.

My composer was outdated, this does not happen anymore.

2023-09-14 07:30 UTC, blizzz commented
> Also why the symfony/console bump in stable27 that was not done in master first?

Tests result complained about PHP 8.2 incompatibilities, so that was a try. That's also why I wonder why they work in master.

2023-09-14 08:06 UTC, blizzz commented
As discussused wiht @come-nc  we'll use  https://github.com/nextcloud/updater/pull/492 for an immediate fix with green CI and he'll do an  follow up with freshing up tests. The fundamental techniques of the updater are still tested, there is only very little interaction with business logic, and master still succeeds.

2023-09-14 08:06 UTC, closed without merging